{ basePython }:

{
  python = "==${basePython.version}";

  addict = "*";
  aiohttp = "*";
  albumentations = "*";
  cupy-cuda12x = "*";
  einops = "*";
  filelock = "*";
  ftfy = "*";
  fvcore = "*";
  huggingface-hub = "*";
  importlib-metadata = "*";
  insightface = "*";
  kornia = ">=0.7.1";
  mediapipe = "*";
  numpy = "*";
  omegaconf = "*";
  onnx = ">=1.14.0";
  onnxruntime = "*";
  opencv-python = "==4.7.0.72";
  packaging = "*";
  pillow = "*";
  psutil = "*";
  python-dateutil = "*";
  pyyaml = "*";
  requests = "*";
  safetensors = ">=0.4.2";
  scikit-image = "*";
  scikit-learn = "*";
  scipy = "*";
  segment-anything = "*";
  soundfile = "*";
  spandrel = "*";
  spandrel-extra-arches = "*";
  svglib = "*";
  torch = "*";
  torchaudio = "*";
  torchsde = "*";
  torchvision = "*";
  tqdm = "*";
  transformers = ">=4.25.1";
  trimesh = "*";
  ultralytics = "*";
  yacs = "*";
  yapf = "*";
}
